services:
  # Servicio web (tu aplicación PHP)
  - type: web
    name: desaparecidos-app
    runtime: php
    buildCommand: composer install
    startCommand: apache2-foreground
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: 
      - key: DB_NAME
        value: desaparecidos_db
    plan: free
